name: build package (kotlin)

on:
  pull_request:
    paths:
      - 'kotlin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Build package
      run: ./gradlew build
