name: PR label check
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

permissions: read-all

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: satvik-s/pr-label-check@1.0.0
        with:
          labels: Kotlin,TypeScript
          type: any_of
