name: create release and publish package (kotlin)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-gh-release:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
    - uses: actions/checkout@v3
    - name: Get release tag
      id: get-release-tag
      shell: bash
      run: echo "::set-output name=release-tag::v$(grep "version =" build.gradle.kts | cut -d'"' -f2)"
    - name: Create GitHub release
      shell: bash
      run: gh release create $RELEASE_TAG
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RELEASE_TAG: ${{ steps.get-release-tag.outputs.release-tag }}

  publish-gpr:
    needs: create-gh-release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Publish package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
